### ISSUE TITLE
Potentieller Memory Leak beim waterremover

### ISSUE THREAD

**Issue by Postremus** [MrCreeperkopf/OpenWSK#3]
Guten Morgen,

https://github.com/MrCreeperkopf/OpenWSK/blob/master/src/net/thecobix/openwsk/arena/WaterRemoveSystem.java#L80

Dort wird jeder zerstörte Block zur explBlocks liste hinzugefügt.

https://github.com/MrCreeperkopf/OpenWSK/blob/master/src/net/thecobix/openwsk/arena/WaterRemoveSystem.java#L87

Dort wird der Block nur aus explBlocks entfernt, wenn er wasser ist.

-> Die Referenz bleibt also potentiel länger als nötig vorhanden.

**Comment by Exceptionflug** [comment]
Hallo Postremus, vielen Dank für diese Information.
Da dieser Fehler ebenfalls in unserer Netzwerkversion vorhanden ist werde ich demnächst diesen Fehler dort als auch in der öffentlichen Version fixen.

MfG St0n3gr1d
