### ISSUE TITLE
BlockGenerator, Commons

### ISSUE THREAD

**Issue by Postremus** [MrCreeperkopf/OpenWSK#4]
Hey,

Bitte erwähne mich noch als Author von BlockGenerator und Commons...

Beste Grüße
Postremus

**Comment by Exceptionflug** [comment]
Meines Erachtens nach wirst du bei /wsk credits angezeigt:

https://github.com/MrCreeperkopf/OpenWSK/blob/master/src/net/thecobix/openwsk/commands/CommandWSK.java#L103

**Comment by Postremus** [comment]
Hey,

Bitte füge diesen Hinweis auch der Readme hinzu.
Danke.

**Comment by Exceptionflug** [comment]
Wird gleich gemacht.
